# Generated by Django 5.0.2 on 2025-10-29 11:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat"),
        ),
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actuel'),
        ),
        migrations.AddField(
            model_name='product',
            name='dci',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dénomination Commune Internationale'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Stock minimum d'alerte"),
        ),
        migrations.AddField(
            model_name='product',
            name='therapeutic_class',
            field=models.CharField(choices=[('analgesic', 'Analgésique'), ('antibiotic', 'Antibiotique'), ('antihypertensive', 'Antihypertenseur'), ('antidiabetic', 'Antidiabétique'), ('antiinflammatory', 'Anti-inflammatoire'), ('gastrointestinal', 'Traitement Gastro-intestinal'), ('respiratory', 'Traitement Respiratoire'), ('dermatological', 'Dermatologique'), ('vitamin', 'Vitamines et Suppléments'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Classe thérapeutique'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité dans le lot')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat du lot")),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='Date de réception')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Lot de produit',
                'verbose_name_plural': 'Lots de produits',
                'ordering': ['expiry_date'],
            },
        ),
    ]
