# Generated by Django 5.0.2 on 2025-10-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_product_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Vente'), ('receipt', 'Réception'), ('adjustment', 'Ajustement'), ('return', 'Retour'), ('damage', 'Produit endommagé'), ('expiry', 'Produit expiré')], max_length=20)),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('previous_stock', models.IntegerField(verbose_name='Stock précédent')),
                ('new_stock', models.IntegerField(verbose_name='Nouveau stock')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('reason', models.TextField(blank=True, verbose_name='Raison')),
                ('created_by', models.CharField(default='Système', max_length=100, verbose_name='Effectué par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
