# Generated by Django 5.0.2 on 2025-10-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseorder_supplier_productbatch_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Code-barres EAN-13 ou autre format', max_length=50, unique=True, verbose_name='Code-barres'),
        ),
    ]
