# Generated by Django 5.0.2 on 2025-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Code-barres EAN-13 ou autre format', max_length=50, null=True, unique=True, verbose_name='Code-barres'),
        ),
    ]
